//Types for Manual Login
export const LOGIN_REQUEST_REQUEST = 'LOGIN_REQUEST_REQUEST';
export const LOGIN_REQUEST_SUCCESS = 'LOGIN_REQUEST_SUCCESS';
export const LOGIN_REQUEST_FAILURE = 'LOGIN_REQUEST_FAILURE';

//Types for Social Login
export const SOCIAL_LOGIN_REQUEST = 'SOCIAL_LOGIN_REQUEST';
export const SOCIAL_LOGIN_REQUEST_SUCCESS = 'SOCIAL_LOGIN_REQUEST_SUCCESS';
export const SOCIAL_LOGIN_REQUEST_FAILURE = 'SOCIAL_LOGIN_REQUEST_FAILURE';

//Update for Social Profile Action
export const UPDATE_SOCIAL_PROFILE_REQ = 'UPDATE_SOCIAL_PROFILE_REQ';
export const UPDATE_SOCIAL_PROFILE_REQ_SUCCESS =
  'UPDATE_SOCIAL_PROFILE_REQ_SUCCESS';
export const UPDATE_SOCIAL_PROFILE_REQ_FAILURE =
  'UPDATE_SOCIAL_PROFILE_REQ_FAILURE';

//Types for Sign Up
export const SIGNUP_REQUEST_REQUEST = 'SIGNUP_REQUEST_REQUEST';
export const SIGNUP_SUCCESS_REQUEST = 'SIGNUP_SUCCESS_REQUEST';
export const SIGNUP_FAILURE_REQUEST = 'SIGNUP_FAILURE_REQUEST';

//Types for Get Car Specs
export const GET_CAR_SPECS_REQUEST = 'GET_CAR_SPECS_REQUEST';
export const GET_CAR_SPECS_REQUEST_SUCCESS = 'GET_CAR_SPECS_REQUEST_SUCCESS';
export const GET_CAR_SPECS_REQUEST_FAILURE = 'GET_CAR_SPECS_REQUEST_FAILURE';

//Types for Create Car Profile
export const CAR_PROFILE_REQUEST = 'CAR_PROFILE_REQUEST';
export const CAR_PROFILE_REQUEST_SUCCESS = 'CAR_PROFILE_REQUEST_SUCCESS';
export const CAR_PROFILE_REQUEST_FAILURE = 'CAR_PROFILE_REQUEST_FAILURE';

//Types for  forgot password
export const FORGOT_PASSWORD_REQUEST = 'FORGOT_PASSWORD_REQUEST';
export const FORGOT_PASSWORD_SUCCESS = 'FORGOT_PASSWORD_SUCCESS';
export const FORGOT_PASSWORD_FAILURE = 'FORGOT_PASSWORD_FAILURE';

//Types for OTP Verification
export const OTP_VERIFY_REQUEST = 'OTP_VERIFY_REQUEST';
export const OTP_VERIFY_SUCCESS = 'OTP_VERIFY_SUCCESS';
export const OTP_VERIFY_FAILURE = 'OTP_VERIFY_FAILURE';

//Types for  Resend OTP
export const RESEND_OTP_REQUEST = 'RESEND_OTP_REQUEST';
export const RESEND_OTP_SUCCESS = 'RESEND_OTP_SUCCESS';
export const RESEND_OTP_FAILURE = 'RESEND_OTP_FAILURE';

//Types for reset password
export const RESET_PASSWORD_REQUEST = 'RESET_PASSWORD_REQUEST';
export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS';
export const RESET_PASSWORD_FAILURE = 'RESET_PASSWORD_FAILURE';

//Types for Logout
export const LOGOUT_REQUEST_REQUEST = 'LOGOUT_REQUEST_REQUEST';
export const LOGOUT_REQUEST_SUCCESS = 'LOGOUT_REQUEST_SUCCESS';
export const LOGOUT_REQUEST_FAILURE = 'LOGOUT_REQUEST_FAILURE';
