//Get profile
export const GET_PROFILE_REQUEST = 'GET_PROFILE_REQUEST';
export const GET_PROFILE_REQUEST_SUCCESS = 'GET_PROFILE_REQUEST_SUCCESS';
export const GET_PROFILE_REQUEST_FAILURE = 'GET_PROFILE_REQUEST_FAILURE';

//Update profile
export const UPDATE_PROFILE_REQUEST = 'UPDATE_PROFILE_REQUEST';
export const UPDATE_PROFILE_REQUEST_SUCCESS = 'UPDATE_PROFILE_REQUEST_SUCCESS';
export const UPDATE_PROFILE_REQUEST_FAILURE = 'UPDATE_PROFILE_REQUEST_FAILURE';

//Get car info
export const GET_CAR_INFO_REQUEST = 'GET_CAR_INFO_REQUEST';
export const GET_CAR_INFO_REQUEST_SUCCESS = 'GET_CAR_INFO_REQUEST_SUCCESS';
export const GET_CAR_INFO_REQUEST_FAILURE = 'GET_CAR_INFO_REQUEST_FAILURE';

//Update car info
export const UPADTE_CAR_INFO_REQUEST = 'UPADTE_CAR_INFO_REQUEST';
export const UPADTE_CAR_INFO_REQUEST_SUCCESS =
  'UPADTE_CAR_INFO_REQUEST_SUCCESS';
export const UPADTE_CAR_INFO_REQUEST_FAILURE =
  'UPADTE_CAR_INFO_REQUEST_FAILURE';

//Get quick chats
export const GET_QUICK_CHATS_REQUEST = 'GET_QUICK_CHATS_REQUEST';
export const GET_QUICK_CHATS_REQUEST_SUCCESS =
  'GET_QUICK_CHATS_REQUEST_SUCCESS';
export const GET_QUICK_CHATS_REQUEST_FAILURE =
  'GET_QUICK_CHATS_REQUEST_FAILURE';

//Add quick chat
export const ADD_QUICK_CHAT_REQUEST = 'ADD_QUICK_CHAT_REQUEST';
export const ADD_QUICK_CHAT_REQUEST_SUCCESS = 'ADD_QUICK_CHAT_REQUEST_SUCCESS';
export const ADD_QUICK_CHAT_REQUEST_FAILURE = 'ADD_QUICK_CHAT_REQUEST_FAILURE';

//Edit quick chat
export const EDIT_QUICK_CHAT_REQUEST = 'EDIT_QUICK_CHAT_REQUEST';
export const EDIT_QUICK_CHAT_REQUEST_SUCCESS =
  'EDIT_QUICK_CHAT_REQUEST_SUCCESS';
export const EDIT_QUICK_CHAT_REQUEST_FAILURE =
  'EDIT_QUICK_CHAT_REQUEST_FAILURE';

//Remove quick chat
export const REMOVE_QUICK_CHAT_REQUEST = 'REMOVE_QUICK_CHAT_REQUEST';
export const REMOVE_QUICK_CHAT_REQUEST_SUCCESS =
  'REMOVE_QUICK_CHAT_REQUEST_SUCCESS';
export const REMOVE_QUICK_CHAT_REQUEST_FAILURE =
  'REMOVE_QUICK_CHAT_REQUEST_FAILURE';

//Static pages
export const STATIC_PAGES_REQUEST = 'STATIC_PAGES_REQUEST';
export const STATIC_PAGES_SUCCESS = 'STATIC_PAGES_SUCCESS';
export const STATIC_PAGES_FAILURE = 'STATIC_PAGES_FAILURE';
